title: Cours de Deep reinforcement learning, Université Lyon 1, M2 IA
description: Cours de Deep reinforcement learning (DRL) à destination des M2 IA de l'université Claude Bernard Lyon 1. 
Le projet consiste à implémenter un algorithme de DRL et l'appliquer sur un benchmark Atari.
theme: jekyll-theme-slate
