title: Cours de Deep reinforcement learning, Université Lyon 1, M2 IA
description: Cours de Deep reinforcement learning (DRL) à destination des M2 IA de l'université Claude Bernard Lyon 1. 
theme: jekyll-theme-slate
